/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu;

import java.awt.Color;
import logica.Controladora;

/**

 @author gianm
 */
public class Principal extends javax.swing.JFrame {
    Controladora control;
    /**
     Creates new form PantallaPeluqueriaCanina
     */
    public Principal(Controladora control) {
        initComponents();
        this.control = control;
    }

    /**
     This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        datos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        lblClienteNum = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblNombreAnimal = new javax.swing.JLabel();
        txtNombreAnimal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblRaza = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblAlergico = new javax.swing.JLabel();
        cbAlergico = new javax.swing.JComboBox<>();
        lblAtencionEspecial = new javax.swing.JLabel();
        cbAtencionEspecial = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        lblNombreDuenio = new javax.swing.JLabel();
        txtNombreDuenio = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblCelularDuenio = new javax.swing.JLabel();
        txtCelularDuenio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        logoPeluqueria = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        lblGuardar = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        barraSuperior = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(915, 600));
        BG.setPreferredSize(new java.awt.Dimension(915, 600));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datos.setBackground(new java.awt.Color(35, 55, 73));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setToolTipText("");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPixelArt[50x50].png"))); // NOI18N

        lblClienteNum.setBackground(new java.awt.Color(35, 55, 73));
        lblClienteNum.setForeground(new java.awt.Color(204, 204, 204));
        lblClienteNum.setText("Cliente Nº:");

        txtCliente.setEditable(false);
        txtCliente.setBackground(new java.awt.Color(35, 55, 73));
        txtCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(130, 130, 130));
        txtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCliente.setText("Nº Cliente [AUTO]");
        txtCliente.setBorder(null);
        txtCliente.setFocusable(false);
        txtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtClienteMousePressed(evt);
            }
        });

        lblNombreAnimal.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblNombreAnimal.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreAnimal.setText("Nombre");

        txtNombreAnimal.setBackground(new java.awt.Color(35, 55, 73));
        txtNombreAnimal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreAnimal.setForeground(new java.awt.Color(130, 130, 130));
        txtNombreAnimal.setText("Nombre de la mascota");
        txtNombreAnimal.setBorder(null);
        txtNombreAnimal.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombreAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreAnimalMousePressed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lblRaza.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblRaza.setForeground(new java.awt.Color(204, 204, 204));
        lblRaza.setText("Raza");

        txtRaza.setBackground(new java.awt.Color(35, 55, 73));
        txtRaza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtRaza.setForeground(new java.awt.Color(130, 130, 130));
        txtRaza.setText("Raza del perro");
        txtRaza.setBorder(null);
        txtRaza.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRaza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRazaMousePressed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        lblColor.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblColor.setForeground(new java.awt.Color(204, 204, 204));
        lblColor.setText("Color");

        txtColor.setBackground(new java.awt.Color(35, 55, 73));
        txtColor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtColor.setForeground(new java.awt.Color(130, 130, 130));
        txtColor.setText("Color del perro");
        txtColor.setBorder(null);
        txtColor.setCaretColor(new java.awt.Color(255, 255, 255));
        txtColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtColorMousePressed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        lblAlergico.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblAlergico.setForeground(new java.awt.Color(204, 204, 204));
        lblAlergico.setText("Alergico");

        cbAlergico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "No", "Si" }));
        cbAlergico.setToolTipText("");
        cbAlergico.setBorder(null);

        lblAtencionEspecial.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblAtencionEspecial.setForeground(new java.awt.Color(204, 204, 204));
        lblAtencionEspecial.setText("Atención Especial");

        cbAtencionEspecial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "No", "Si" }));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        lblNombreDuenio.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblNombreDuenio.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreDuenio.setText("Nombre Dueño");

        txtNombreDuenio.setBackground(new java.awt.Color(35, 55, 73));
        txtNombreDuenio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreDuenio.setForeground(new java.awt.Color(130, 130, 130));
        txtNombreDuenio.setText("Nombre del dueño");
        txtNombreDuenio.setBorder(null);
        txtNombreDuenio.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombreDuenio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreDuenioMousePressed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        lblCelularDuenio.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblCelularDuenio.setForeground(new java.awt.Color(204, 204, 204));
        lblCelularDuenio.setText("Celular Dueño");

        txtCelularDuenio.setBackground(new java.awt.Color(35, 55, 73));
        txtCelularDuenio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCelularDuenio.setForeground(new java.awt.Color(130, 130, 130));
        txtCelularDuenio.setText("1111111111");
        txtCelularDuenio.setBorder(null);
        txtCelularDuenio.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCelularDuenio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCelularDuenioMousePressed(evt);
            }
        });
        txtCelularDuenio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularDuenioKeyTyped(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        lblObservaciones.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(204, 204, 204));
        lblObservaciones.setText("Observaciones");

        txtObservaciones.setBackground(new java.awt.Color(35, 55, 73));
        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(130, 130, 130));
        txtObservaciones.setRows(5);
        txtObservaciones.setText("Observaciones...");
        txtObservaciones.setCaretColor(new java.awt.Color(255, 255, 255));
        txtObservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObservacionesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservaciones);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(30, 48, 63));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout datosLayout = new javax.swing.GroupLayout(datos);
        datos.setLayout(datosLayout);
        datosLayout.setHorizontalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNombreDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosLayout.createSequentialGroup()
                                .addComponent(lblAlergico)
                                .addGap(18, 18, 18)
                                .addComponent(cbAlergico, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(lblAtencionEspecial)
                                .addGap(18, 18, 18)
                                .addComponent(cbAtencionEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombreDuenio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObservaciones, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRaza, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCelularDuenio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelularDuenio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaza, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblColor))))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClienteNum)
                            .addComponent(lblNombreAnimal))
                        .addGap(18, 18, 18)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo)
                        .addContainerGap())
                    .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombreAnimal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))))
            .addGroup(datosLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        datosLayout.setVerticalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClienteNum)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAnimal)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(logo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergico)
                    .addComponent(lblAtencionEspecial)
                    .addComponent(cbAtencionEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlergico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreDuenio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCelularDuenio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCelularDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        BG.add(datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        jPanel2.setBackground(new java.awt.Color(71, 225, 174));
        jPanel2.setPreferredSize(new java.awt.Dimension(315, 600));

        titulo.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(18, 79, 134));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("PELUQUERÍA");

        titulo1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        titulo1.setForeground(new java.awt.Color(18, 79, 134));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("CANINA");

        logoPeluqueria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoPeluqueria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPeluqueria.png"))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(50, 76, 59));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        lblGuardar.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuardar.setText("GUARDAR");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
            .addGroup(btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnGuardarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblGuardar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
            .addGroup(btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnGuardarLayout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(lblGuardar)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        btnLimpiar.setBackground(new java.awt.Color(50, 76, 59));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });

        lblLimpiar.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiar.setText("LIMPIAR");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
            .addGroup(btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLimpiarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblLimpiar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLimpiarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblLimpiar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPeluqueria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoPeluqueria, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        BG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 315, 600));

        barraSuperior.setBackground(new java.awt.Color(60, 191, 147));
        barraSuperior.setPreferredSize(new java.awt.Dimension(915, 30));
        barraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraSuperiorMouseDragged(evt);
            }
        });
        barraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraSuperiorMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(60, 191, 147));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setPreferredSize(new java.awt.Dimension(33, 33));

        lblSalir.setBackground(new java.awt.Color(60, 191, 147));
        lblSalir.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(0, 0, 0));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("X");
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        BG.add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 915, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    //<editor-fold desc="Barra (header) hecha por mí">
    int xMouse, yMouse;
    private void barraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraSuperiorMousePressed

    private void barraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraSuperiorMouseDragged

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        btnSalir.setBackground(Color.red);
        lblSalir.setForeground(Color.white);
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        btnSalir.setBackground(new Color(60, 191, 147));
        lblSalir.setForeground(Color.black);
    }//GEN-LAST:event_lblSalirMouseExited
    //</editor-fold>
    
    //<editor-fold desc="Botón guardar y botón limpiar">
    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(56,114,77));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(50,76,59));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String nombrePerro = null, raza = null, color = null, alergico = null, atencion = null, nombreDuenio = null, obser = null;
        int numCelular = -1;
        if(!txtNombreAnimal.getText().equals("Nombre de la mascota")){nombrePerro = txtNombreAnimal.getText();}
        if(!txtRaza.getText().equals("Raza del perro")){raza = txtRaza.getText();}
        if(!txtColor.getText().equals("Color del perro")){color = txtColor.getText();}
        if(!cbAlergico.getSelectedItem().equals("-")){alergico = cbAlergico.getSelectedItem().toString();}
        if(!cbAtencionEspecial.getSelectedItem().equals("-")){atencion = cbAtencionEspecial.getSelectedItem().toString();}
        if(!txtNombreDuenio.getText().equals("Nombre del dueño")){nombreDuenio = txtNombreDuenio.getText();}
        if(!txtCelularDuenio.getText().equals("1111111111")){numCelular = Integer.parseInt(txtCelularDuenio.getText());}
        if(!txtObservaciones.getText().equals("Observaciones...")){obser = txtObservaciones.getText();}
        
        if((nombrePerro != null) && (raza != null) && (nombreDuenio != null) && (numCelular != -1)){
            try{
                control.crearMascota(nombrePerro, raza, color, alergico, atencion, nombreDuenio, numCelular, obser);
            }catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, e);
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "Los campos \"Nombre\", \"Raza\", \"Nombre Dueño\" y \"Celular Dueño\", no pueden estar vacíos.", "ERROR!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        btnLimpiar.setBackground(new Color(56,114,77));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        btnLimpiar.setBackground(new Color(50,76,59));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        txtCliente.setText("Nº Cliente [AUTO]");
        txtNombreAnimal.setText("Nombre de la mascota");
        txtRaza.setText("Raza del perro");
        txtColor.setText("Color del perro");
        cbAlergico.setSelectedIndex(0);
        cbAtencionEspecial.setSelectedIndex(0);
        txtNombreDuenio.setText("Nombre del dueño");
        txtCelularDuenio.setText("1111111111");
        txtObservaciones.setText("Observaciones...");
        
        txtCliente.setForeground(new Color(130,130,130));
        txtNombreAnimal.setForeground(new Color(130,130,130));
        txtRaza.setForeground(new Color(130,130,130));
        txtColor.setForeground(new Color(130,130,130));
        txtNombreDuenio.setForeground(new Color(130,130,130));
        txtCelularDuenio.setForeground(new Color(130,130,130));
        txtObservaciones.setForeground(new Color(130,130,130));
        
    }//GEN-LAST:event_btnLimpiarMouseClicked
    //</editor-fold>
    
    //<editor-fold desc="Texto pre-definido de los TextField">
    private void txtClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClienteMousePressed
        if(txtNombreAnimal.getText().isEmpty()){
            txtNombreAnimal.setText("Nombre de la mascota");
            txtNombreAnimal.setForeground(new Color(130,130,130));
        }
        if(txtRaza.getText().isEmpty()){
            txtRaza.setText("Raza del perro");
            txtRaza.setForeground(new Color(130,130,130));
        }
        if(txtColor.getText().isEmpty()){
            txtColor.setText("Color del perro");
            txtColor.setForeground(new Color(130,130,130));
        }
        if(txtNombreDuenio.getText().isEmpty()){
            txtNombreDuenio.setText("Nombre del dueño");
            txtNombreDuenio.setForeground(new Color(130,130,130));
        }
        if(txtCelularDuenio.getText().isEmpty()){
            txtCelularDuenio.setText("1111111111");
            txtCelularDuenio.setForeground(new Color(130,130,130));
        }
        if(txtObservaciones.getText().isEmpty()){
            txtObservaciones.setText("Observaciones...");
            txtObservaciones.setForeground(new Color(130,130,130));
        }
    }//GEN-LAST:event_txtClienteMousePressed

    private void txtNombreAnimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreAnimalMousePressed
        if(txtCliente.getText().isEmpty()){
            txtCliente.setText("Nº Cliente [AUTO]");
            txtCliente.setForeground(new Color(130,130,130));
        }
        if(txtNombreAnimal.getText().equals("Nombre de la mascota")){
            txtNombreAnimal.setText("");
            txtNombreAnimal.setForeground(Color.white);
        }
        if(txtRaza.getText().isEmpty()){
            txtRaza.setText("Raza del perro");
            txtRaza.setForeground(new Color(130,130,130));
        }
        if(txtColor.getText().isEmpty()){
            txtColor.setText("Color del perro");
            txtColor.setForeground(new Color(130,130,130));
        }
        if(txtNombreDuenio.getText().isEmpty()){
            txtNombreDuenio.setText("Nombre del dueño");
            txtNombreDuenio.setForeground(new Color(130,130,130));
        }
        if(txtCelularDuenio.getText().isEmpty()){
            txtCelularDuenio.setText("1111111111");
            txtCelularDuenio.setForeground(new Color(130,130,130));
        }
        if(txtObservaciones.getText().isEmpty()){
            txtObservaciones.setText("Observaciones...");
            txtObservaciones.setForeground(new Color(130,130,130));
        }
    }//GEN-LAST:event_txtNombreAnimalMousePressed

    private void txtRazaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRazaMousePressed
        if(txtCliente.getText().isEmpty()){
            txtCliente.setText("Nº Cliente [AUTO]");
            txtCliente.setForeground(new Color(130,130,130));
        }
        if(txtNombreAnimal.getText().isEmpty()){
            txtNombreAnimal.setText("Nombre de la mascota");
            txtNombreAnimal.setForeground(new Color(130,130,130));
        }
        if(txtRaza.getText().equals("Raza del perro")){
            txtRaza.setText("");
            txtRaza.setForeground(Color.white);
        }
        if(txtColor.getText().isEmpty()){
            txtColor.setText("Color del perro");
            txtColor.setForeground(new Color(130,130,130));
        }
        if(txtNombreDuenio.getText().isEmpty()){
            txtNombreDuenio.setText("Nombre del dueño");
            txtNombreDuenio.setForeground(new Color(130,130,130));
        }
        if(txtCelularDuenio.getText().isEmpty()){
            txtCelularDuenio.setText("1111111111");
            txtCelularDuenio.setForeground(new Color(130,130,130));
        }
        if(txtObservaciones.getText().isEmpty()){
            txtObservaciones.setText("Observaciones...");
            txtObservaciones.setForeground(new Color(130,130,130));
        }
    }//GEN-LAST:event_txtRazaMousePressed

    private void txtColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColorMousePressed
        if(txtCliente.getText().isEmpty()){
            txtCliente.setText("Nº Cliente [AUTO]");
            txtCliente.setForeground(new Color(130,130,130));
        }
        if(txtNombreAnimal.getText().isEmpty()){
            txtNombreAnimal.setText("Nombre de la mascota");
            txtNombreAnimal.setForeground(new Color(130,130,130));
        }
        if(txtRaza.getText().isEmpty()){
            txtRaza.setText("Raza del perro");
            txtRaza.setForeground(new Color(130,130,130));
        }
        if(txtColor.getText().equals("Color del perro")){
            txtColor.setText("");
            txtColor.setForeground(Color.white);
        }
        if(txtNombreDuenio.getText().isEmpty()){
            txtNombreDuenio.setText("Nombre del dueño");
            txtNombreDuenio.setForeground(new Color(130,130,130));
        }
        if(txtCelularDuenio.getText().isEmpty()){
            txtCelularDuenio.setText("1111111111");
            txtCelularDuenio.setForeground(new Color(130,130,130));
        }
        if(txtObservaciones.getText().isEmpty()){
            txtObservaciones.setText("Observaciones...");
            txtObservaciones.setForeground(new Color(130,130,130));
        }
    }//GEN-LAST:event_txtColorMousePressed

    private void txtNombreDuenioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreDuenioMousePressed
        if(txtCliente.getText().isEmpty()){
            txtCliente.setText("Nº Cliente [AUTO]");
            txtCliente.setForeground(new Color(130,130,130));
        }
        if(txtNombreAnimal.getText().isEmpty()){
            txtNombreAnimal.setText("Nombre de la mascota");
            txtNombreAnimal.setForeground(new Color(130,130,130));
        }
        if(txtRaza.getText().isEmpty()){
            txtRaza.setText("Raza del perro");
            txtRaza.setForeground(new Color(130,130,130));
        }
        if(txtColor.getText().isEmpty()){
            txtColor.setText("Color del perro");
            txtColor.setForeground(new Color(130,130,130));
        }
        if(txtNombreDuenio.getText().equals("Nombre del dueño")){
            txtNombreDuenio.setText("");
            txtNombreDuenio.setForeground(Color.white);
        }
        if(txtCelularDuenio.getText().isEmpty()){
            txtCelularDuenio.setText("1111111111");
            txtCelularDuenio.setForeground(new Color(130,130,130));
        }
        if(txtObservaciones.getText().isEmpty()){
            txtObservaciones.setText("Observaciones...");
            txtObservaciones.setForeground(new Color(130,130,130));
        }
    }//GEN-LAST:event_txtNombreDuenioMousePressed

    private void txtCelularDuenioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCelularDuenioMousePressed
        if(txtCliente.getText().isEmpty()){
            txtCliente.setText("Nº Cliente [AUTO]");
            txtCliente.setForeground(new Color(130,130,130));
        }
        if(txtNombreAnimal.getText().isEmpty()){
            txtNombreAnimal.setText("Nombre de la mascota");
            txtNombreAnimal.setForeground(new Color(130,130,130));
        }
        if(txtRaza.getText().isEmpty()){
            txtRaza.setText("Raza del perro");
            txtRaza.setForeground(new Color(130,130,130));
        }
        if(txtColor.getText().isEmpty()){
            txtColor.setText("Color del perro");
            txtColor.setForeground(new Color(130,130,130));
        }
        if(txtNombreDuenio.getText().isEmpty()){
            txtNombreDuenio.setText("Nombre del dueño");
            txtNombreDuenio.setForeground(new Color(130,130,130));
        }
        if(txtCelularDuenio.getText().equals("1111111111")){
            txtCelularDuenio.setText("");
            txtCelularDuenio.setForeground(Color.white);
        }
        if(txtObservaciones.getText().isEmpty()){
            txtObservaciones.setText("Observaciones...");
            txtObservaciones.setForeground(new Color(130,130,130));
        }
    }//GEN-LAST:event_txtCelularDuenioMousePressed

    private void txtObservacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObservacionesMousePressed
        if(txtCliente.getText().isEmpty()){
            txtCliente.setText("Nº Cliente [AUTO]");
            txtCliente.setForeground(new Color(130,130,130));
        }
        if(txtNombreAnimal.getText().isEmpty()){
            txtNombreAnimal.setText("Nombre de la mascota");
            txtCliente.setForeground(new Color(130,130,130));
        }
        if(txtRaza.getText().isEmpty()){
            txtRaza.setText("Raza del perro");
            txtRaza.setForeground(new Color(130,130,130));
        }
        if(txtColor.getText().isEmpty()){
            txtColor.setText("Color del perro");
            txtColor.setForeground(new Color(130,130,130));
        }
        if(txtNombreDuenio.getText().isEmpty()){
            txtNombreDuenio.setText("Nombre del dueño");
            txtNombreDuenio.setForeground(new Color(130,130,130));
        }
        if(txtCelularDuenio.getText().isEmpty()){
            txtCelularDuenio.setText("1111111111");
            txtCelularDuenio.setForeground(new Color(130,130,130));
        }
        if(txtObservaciones.getText().equals("Observaciones...")){
            txtObservaciones.setText("");
            txtObservaciones.setForeground(Color.white);
        }
    }//GEN-LAST:event_txtObservacionesMousePressed

    private void txtCelularDuenioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularDuenioKeyTyped
        char key = evt.getKeyChar();
        if(txtCelularDuenio.getText().length() < 10){if(key < '0' || key > '9'){evt.consume();}}
        else{evt.consume();}
    }//GEN-LAST:event_txtCelularDuenioKeyTyped
    //</editor-fold>
    
    
    
    //<editor-fold desc="Variables declaration - do not modify ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JComboBox<String> cbAlergico;
    private javax.swing.JComboBox<String> cbAtencionEspecial;
    private javax.swing.JPanel datos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAlergico;
    private javax.swing.JLabel lblAtencionEspecial;
    private javax.swing.JLabel lblCelularDuenio;
    private javax.swing.JLabel lblClienteNum;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblNombreAnimal;
    private javax.swing.JLabel lblNombreDuenio;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoPeluqueria;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JTextField txtCelularDuenio;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNombreAnimal;
    private javax.swing.JTextField txtNombreDuenio;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
